# Generated by Django 4.1 on 2022-08-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_alter_company_company_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary_end',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary_start',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
