# Generated by Django 4.1 on 2022-08-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_alter_vacancy_vacancy_count_alter_worker_salary_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_count',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='vacancy_count',
        ),
    ]
