# Generated by Django 4.1 on 2022-08-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_remove_company_company_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='min_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
