# Generated by Django 4.1 on 2022-08-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_category_max_price_category_min_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='min_price',
        ),
    ]
